# Generated by Django 4.0.2 on 2022-02-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='blurb',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='team',
            name='collab_prompt',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='team',
            name='custom_prompt',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='team',
            name='required_fields',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
